### ISSUE TITLE
Can you add support for Python bytecode 3.10 and above 

### ISSUE THREAD

**Issue by DarkHorse-APP2** [FuturisticGoo/UnPYC#2]
I need to decompile a Python bytecode 3.10 version

**Comment by FuturisticGoo** [comment]
Unfortunately this isn't something I can do. This project uses [uncompyle6](https://github.com/rocky/python-uncompyle6) package and that doesn't support Python >= 3.9  
Please don't create an issue there because the owner of uncompyle6 has already given their reasons for not supporting the newer Python versions.
